### ISSUE TITLE
Usage of `inspect` module in elm/earthio/xarray_filters

### ISSUE THREAD

**Issue by PeterDSteinberg** [ContinuumIO/xarray_filters#12]
In PR #8, we had a failure in `inspect` methods in 2.7 vs 3.*.  

 * [x] See [this build from PR 8](https://travis-ci.org/ContinuumIO/xarray_filters/jobs/273491024#L1546) and come up with alternate method
 * [x] Look at usage of `inspect` more generally, e.g are there Python 2.7 vs 3.5 issues in `func_signatures.py` of `xarray_filters` that uses `inspect`?  
   * Note: the `func_signatures.py` in this repo is a copy from `elm` -> `earthio` -> `xarray_filters` and there may be a copy of `func_signatures.py` still in `elm` /`earthio` during the transition.  The `func_signatures.py` in this repo is the one we should be fixing.

**Comment by gbrener** [comment]
@gpfreitas , what's the status of this issue? Can we close it (do we have Python2 compatibility)? If not, I can work on this today.

**Comment by gbrener** [comment]
Addressed in #33. Once Python 2.7 tests are passing, I'm considering this issue "resolved" unless otherwise noted.
