### ISSUE TITLE
Consolidate examples

### ISSUE THREAD

**Issue by PeterDSteinberg** [ContinuumIO/xarray_filters#24]
@gpfreitas  Can you move this [example of datasets.py](https://github.com/ContinuumIO/xarray_filters/blob/master/xarray_filters/examples/20170905_Nasa_meeting_demo_xarray_filters.ipynb) to the top level `notebooks` dir of the repo.

**Comment by gbrener** [comment]
Addressed in #32. Closing once it's merged.

**Comment by gbrener** [comment]
Updated #28 as well.
