### ISSUE TITLE
Implement MLDataset.load(), optionally using earthio.load_layers()

### ISSUE THREAD

**Issue by gbrener** [ContinuumIO/xarray_filters#43]
From https://github.com/ContinuumIO/earthio/issues/31#issuecomment-341821415 , @PeterDSteinberg and I agreed that we'd keep `xarray_filters` decoupled from `earthio` by exposing a method called `load()` from the `MLDataset` class, which would infer - or accept as an option - the type of data being loaded, and call `earthio.load_layers()` as an implementation detail if strictly necessary.

**Comment by PeterDSteinberg** [comment]
Fixed by #44
