### ISSUE TITLE
Relative vs absolute imports

### ISSUE THREAD

**Issue by gpfreitas** [ContinuumIO/xarray_filters#9]
@PeterDSteinberg, @gbrener 

As of commit 1d9b2aaebbfd14ca71464788c33b490884142aec we have some files with relative imports (like `xarray_filters/datasets.py) and others with absolute imports (like `mldatasets.py`).

 Which one are we going to use?

**Comment by gbrener** [comment]
@gpfreitas I don't see the relative imports you're referring to, but I believe we're using absolute imports. Please feel free to change relative to absolute, as the relative imports were probably just an oversight introduced while making changes quickly.

**Comment by PeterDSteinberg** [comment]
I agree with @gbrener and think we should go with absolute imports

**Comment by gbrener** [comment]
I came across the [scikit-learn coding guidelines](http://scikit-learn.org/stable/developers/contributing.html#coding-guidelines) today, and here is what they say on the subject:

> Use relative imports for references inside scikit-learn.

So if we wanted to emulate their development style, we'd use absolute imports for libraries outside of `elm`/`earthio`/`xarray_filters`, and relative imports for internal modules. Personally, I think sticking to absolute imports throughout is simpler and more Pythonic (https://www.python.org/dev/peps/pep-0328/#abstract), but I'd be willing to switch to the scikit-learn approach if we found ourselves doing a lot of cross-module refactors. What do you think @gpfreitas?

**Comment by gpfreitas** [comment]
I looked into bokeh, xarray and dask today and they also follow the sklearn approach (explicit relative imports). Dave Beaszley also encourages use of relative imports (see the PDF of [his talk](http://www.dabeaz.com/modulepackage/), pages 40-46)

Pandas seems to go the other way: absolute imports all the way.

Django has an interesting mix... it seems to import subpackages (inside django) absolutely, and use explicit relative imports for modules inside the same subpackage. I'd love to know _why_.

The standard library seems to be a mix, with a higher likelihood of relative imports for recent code (like asyncio) and absolute imports for older code (like urllib). Again, relative imports only inside a package.

I don't have a full picture of what is better. I like relative imports in principle because:

-  you can rename things outside a module without having to change that module's source... which is nice from a VCS point of view.
- it makes "lazy testing" (not a technical term!) easy. For example, I could just run `import xarray_filters` from the top of the git repo and get the latest edits, without having to install a package.
- it seems to be more used in more modern codebases

Happy to go either way.

**Comment by gbrener** [comment]
@gpfreitas Thanks for the detailed response. More food for thought:
- PEP-8: https://www.python.org/dev/peps/pep-0008/#imports
- Google Python Style Guide: https://google.github.io/styleguide/pyguide.html#Imports
Either way, since neither of us feel strongly about it, @PeterDSteinberg breaks the tie :)
